# SwiftLint Configuration
# See: https://realm.github.io/SwiftLint/

# 対象ディレクトリ
included:
  - camp_vol5_ios

# 除外するディレクトリ・ファイル
excluded:
  - Pods
  - .build
  - DerivedData
  - '*/Generated'
  - '*.generated.swift'

# 有効化するルール
opt_in_rules:
  - array_init
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - empty_collection_literal
  - empty_count
  - empty_string
  - first_where
  - force_unwrapping
  - implicit_return
  - last_where
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_parameters
  - overridden_super_call
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - sorted_first_last
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

# 無効化するルール
disabled_rules:
  - trailing_whitespace # swift-formatで対応

# ルールのカスタマイズ
line_length:
  warning: 120
  error: 200
  ignores_comments: true
  ignores_urls: true

file_length:
  warning: 500
  error: 1000

function_body_length:
  warning: 60
  error: 100

type_body_length:
  warning: 300
  error: 500

cyclomatic_complexity:
  warning: 10
  error: 20

nesting:
  type_level:
    warning: 2
    error: 3

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - url
    - URL
    - db

type_name:
  min_length: 3
  max_length: 50

# 強制アンラップの警告レベル
force_unwrapping: warning

# 暗黙的なreturnを許可する行数
implicit_return:
  included:
    - closure
    - getter

# その他の設定
reporter: "xcode"
