# SwiftLint Configuration
# See: https://realm.github.io/SwiftLint/

# 対象ディレクトリ
included:
  - camp_vol5_ios

# 除外するディレクトリ・ファイル
excluded:
  - Pods
  - .build
  - DerivedData
  - '*/Generated'
  - '*.generated.swift'

# 有効化するルール
opt_in_rules:
  - array_init
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - empty_collection_literal
  - empty_count
  - empty_string
  - first_where
  # - force_unwrapping  # 一部のケースで必要
  - implicit_return
  - last_where
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_parameters
  - overridden_super_call
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - sorted_first_last
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

# 無効化するルール
disabled_rules:
  - trailing_whitespace # swift-formatで対応
  - multiple_closures_with_trailing_closure # SwiftUIの標準パターンと競合
  - large_tuple # 一部のケースで3要素以上のタプルが便利
  - trailing_comma # swift-formatと競合するため無効化
  - closure_parameter_position # swift-formatと競合するため無効化
  - opening_brace # swift-formatと競合するため無効化

# ルールのカスタマイズ
line_length:
  warning: 120
  error: 200
  ignores_comments: true
  ignores_urls: true

file_length:
  warning: 1000
  error: 2000

function_body_length:
  warning: 120
  error: 200

type_body_length:
  warning: 600
  error: 1000

cyclomatic_complexity:
  warning: 15
  error: 25

nesting:
  type_level:
    warning: 2
    error: 3

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - url
    - URL
    - db
    - _body  # SwiftUI makeBody requirement

type_name:
  min_length: 3
  max_length: 50
  excluded:
    - camp_vol5_iosApp  # Xcode generated App structure
    - crazy_lave_Watch_AppApp  # Xcode generated Watch App structure

# 暗黙的なreturnを許可する行数
implicit_return:
  included:
    - closure
    - getter

# その他の設定
reporter: "xcode"
