# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  tree:
    desc: "Generate directory tree and save to docs/tree.md"
    cmds:
      - mkdir -p docs
      - tree -I 'node_modules|.git|build|DerivedData|*.xcworkspace|*.xcodeproj|Pods' > docs/tree.md
    silent: false
